name: Deploy Flask App to EC2

on:
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up SSH key for connection
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. Add EC2 host to known_hosts to prevent prompt
      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4. Build, copy, and run Docker on EC2
      - name: Deploy Docker container on EC2
        run: |
          scp -o StrictHostKeyChecking=no -r app ec2-user@${{ secrets.EC2_HOST }}:~/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} '
            cd ~/app &&
            docker stop $(docker ps -q --filter ancestor=usama-flask-app) 2>/dev/null || true &&
            docker rm $(docker ps -q --filter ancestor=usama-flask-app) 2>/dev/null || true &&
            docker build -t usama-flask-app . &&
            sudo docker run -d -p 80:5000 usama-flask-app
          '